### ISSUE TITLE
loading  built-in node modules

### ISSUE THREAD

**Issue by tracyhenry** [coveo/nashorn-commonjs-modules#32]
I have succeeded in loading some modules through the file system. However, I'm having trouble loading built-in node modules such as `http` or `url` and any modules that require these. The reason is probably because the root folder I specified does not have these modules under it.  

How should I get around this?

**Comment by malaporte** [comment]
This package isn't a Node JS emulator, as it doesn't provide an implementation for the (many) core NodeJS modules. You can only use it to load JS packages that don't rely on those (ex: packages that are designed to work in a web page, etc.)
