### ISSUE TITLE
require should not enforce prefix to load from file

### ISSUE THREAD

**Issue by abonstu** [coveo/nashorn-commonjs-modules#34]
Currently, the require method enforces (line 115 of Module.class) that all modules loaded from the filesystem must be prefixed with '/', '../' or './'. 

This makes it difficult to import existing modules that in turn require other modules that do not include a prefix.

Can you just remove this check and leave it up to the module loader (i.e. Folder implementation) to determine whether to load from filesystem or not?

**Comment by malaporte** [comment]
As far as I know the algorithm is supposed to mimic Node's behavior, as described here: https://nodejs.org/api/modules.html

You can see that it explicitly looks for a prefix before loading anything from the filesystem. Non-prefixed modules are always loaded from the `node_modules` folder.

This being said, maybe there is something incorrect in the code. Can you provide a sample that works in Node and breaks with this library?

**Comment by abonstu** [comment]
If you've just followed the spec then i guess thats right approach. 

I had my modules stored under a different path (not node_modules), but as mentioned, this meant modules failed to load dependencies as they are typically referenced without a path prefix.

I've now restructured things to use a node_modules directory instead which resolves the issue.

Thanks for your help :)
