### ISSUE TITLE
class fields/methods should be protected, not private

### ISSUE THREAD

**Issue by abonstu** [coveo/nashorn-commonjs-modules#35]
Pretty much all class fields and methods are private which makes it impossible to extend.

Can these be changed to protected instead?

**Comment by malaporte** [comment]
Well, no. Only methods that are explicitly designed to be overridden should be protected. The others are private implementation details and should remain so.

If you can answer my question in the other issue you created it'd help figure out if the behavior change you're looking for is really correct or not...
